### ISSUE TITLE
Unable to deploy to Docker swarm

### ISSUE THREAD

**Issue by bigfoot90** [severalnines/docker-centos-ssh#1]
i'm trying to deploy this container to my Docker environment with swarm mode.
I've configured two networks `cluster` and `app`.
My Application connects to this container throught `app` network, and ClusterControl connects throught `cluster` network.

The problem is that this container sends the **wrong network ip address** to the ClusterControl.
How can I tell to use the correct address IP?

This is my compose file:
```yml
version: '3.4'

services:
  clustercontrol:
    image: severalnines/clustercontrol:1.5
    networks:
      - cluster

  node:
    image: severalnines/centos-ssh
    depends_on:
      - clustercontrol
    environment:
      - CC_HOST=clustercontrol
      - AUTO_DEPLOYMENT=0
    networks:
      - cluster
      - app

networks:
  cluster: ~
  app:
    external: true
```
